import CoreData
import SwiftUI

// MARK: - Supporting Types
private struct HomePick: Equatable {
    // MARK: - Properties
    let identifier: String
    let displayName: String
    let lastConnectedText: String
    let hasConnectedBefore: Bool
    let note: String?
    /// True when this person was already logged as connected today — the card
    /// then shows a calm "Connected today" state instead of the details hint.
    let connectedToday: Bool
}

struct HomeView: View {
    // MARK: - Bindings
    @Binding var selectedTab: AppTab

    // MARK: - Environment
    @Environment(\.managedObjectContext) private var context
    @Environment(\.scenePhase) private var scenePhase
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    // MARK: - State
    @State private var connectErrorMessage: String?
    @State private var showConnectError = false
    @State private var todayPicks: [HomePick] = []
    @State private var showResetConfirm = false
    @State private var monthlyConnectedCount = 0
    @State private var poolWarningText: String?
    @State private var currentStreak = 0
    // The person whose info card is open (tapping a pick pushes it).
    @State private var selectedInfoPerson: Person?

    // Remembers the day we last auto-generated (or the user reset) so opening
    // the app repeatedly doesn't regenerate a set the user cleared on purpose.
    @AppStorage("lastAutoGeneratedDay") private var lastAutoGeneratedDay = ""

    // MARK: - View
    var body: some View {
        NavigationStack {
            VStack(alignment: .leading, spacing: 20) {
                let hasTodayPick = !todayPicks.isEmpty
                // Header
                HomeHeader(
                    greeting: greeting,
                    dateText: todayDateText,
                    streak: currentStreak,
                    canReset: hasTodayPick,
                    onReset: {
                        lightHaptic()
                        showResetConfirm = true
                    }
                )
                .alert("Something Went Wrong", isPresented: $showConnectError) {
                    Button("OK", role: .cancel) { }
                } message: {
                    Text(connectErrorMessage ?? "Something went wrong.")
                }

                if let warning = poolWarningText {
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundStyle(Theme.Palette.warning)
                        Text(warning)
                            .font(.footnote)
                            .foregroundStyle(Theme.Palette.textSecondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(12)
                    .background(
                        RoundedRectangle(cornerRadius: 14, style: .continuous)
                            .fill(Theme.Palette.warning.opacity(0.12))
                    )
                    .accessibilityElement(children: .combine)
                }

                // Today's picks — a light section heading, then a carousel of
                // big cards (one person per card, swipeable when there's more
                // than one). Each card carries its own surface so it reads as
                // the hero of the screen rather than a row inside a box.
                HStack(alignment: .firstTextBaseline) {
                    Text("Today’s picks")
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(Theme.Palette.textPrimary)

                    Spacer()

                    Text(monthlyReachedLabel)
                        .font(.subheadline)
                        .foregroundStyle(Theme.Palette.textSecondary)
                }

                if hasTodayPick {
                    HomePicksCarousel(
                        picks: todayPicks,
                        onOpenDetails: { pick in
                            lightHaptic()
                            openInfoCard(for: pick)
                        },
                        onUndo: { pick in
                            undoConnected(pick)
                        }
                    )
                } else {
                    HomeEmptyState(
                        illustration: "AllDoneMoon",
                        symbol: "hands.sparkles",
                        title: "No pick for today",
                        message: monthlyConnectedCount > 0
                            ? "Tap Generate to create today’s picks. Your monthly progress is still saved."
                            : "Generate a pick or add more people to your pool."
                    )
                    .padding(.vertical, 20)
                    .padding(.horizontal, 12)
                    .frame(maxWidth: .infinity)
                    .cardSurface(radius: 20)
                }

                Spacer(minLength: 12)

                // Action area — one clear primary (Generate). Reset lives in the
                // header's overflow menu, and Pool has its own tab, so nothing
                // competes with the button or crowds the bottom of the screen.
                VStack(spacing: 12) {
                    Button(action: {
                        lightHaptic()
                        generateTodayPick()
                    }) {
                        Label(hasTodayPick ? "Regenerate Picks" : "Generate Picks", systemImage: "sparkles")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(PrimaryPillButtonStyle())
                    .accessibilityHint("Create today’s picks using your current rules.")

                    Text("Small, steady check-ins build real connection.")
                        .font(.footnote)
                        .foregroundStyle(Theme.Palette.textSecondary)
                        .frame(maxWidth: .infinity, alignment: .center)
                        .padding(.top, 2)
                }
                .confirmationDialog(
                    "Reset today’s pick?",
                    isPresented: $showResetConfirm,
                    titleVisibility: .visible
                ) {
                    Button("Reset", role: .destructive) {
                        resetTodayPick()
                    }
                    Button("Cancel", role: .cancel) { }
                } message: {
                    Text("This will remove today’s saved pick and generate a fresh one the next time you tap Generate.")
                }
            }
            .padding()
            .padding(.bottom, Theme.Layout.tabBarClearance)
            .background(Theme.Palette.background.ignoresSafeArea())
            .navigationDestination(item: $selectedInfoPerson) { person in
                ContactHistoryView(person: person, isTodayPick: true)
            }
            .onChange(of: selectedInfoPerson) { _, newValue in
                // On returning from the info card, reload so any connect / mark /
                // snooze / note change made in there is reflected on Home.
                if newValue == nil { refreshTodayPicks() }
            }
            .onAppear {
                loadOrAutoGenerate()
            }
            .onChange(of: selectedTab) { _, newTab in
                if newTab == .home {
                    loadOrAutoGenerate()
                }
            }
            .onChange(of: scenePhase) { _, newPhase in
                if newPhase == .active {
                    loadOrAutoGenerate()
                }
            }
        }
    }

    // MARK: - Derived Values

    /// A warm, time-of-day greeting for the header. Shifts across the day —
    /// morning, afternoon, evening, and a late-night "Good night".
    private var greeting: String {
        switch Calendar.current.component(.hour, from: Date()) {
        case 5..<12: return "Good morning"
        case 12..<17: return "Good afternoon"
        case 17..<21: return "Good evening"
        default: return "Good night"
        }
    }

    private var todayDateText: String {
        Date().formatted(.dateTime.weekday(.wide).month(.abbreviated).day())
    }

    // Warm, forward-looking copy. We deliberately avoid pace/behind framing —
    // the goal is a gentle nudge, never guilt about a number you "should" hit.
    private var monthlyReachedLabel: String {
        switch monthlyConnectedCount {
        case 0:
            return "Reach out to someone today"
        case 1:
            return "1 person reached this month"
        default:
            return "\(monthlyConnectedCount) reached this month"
        }
    }

    // MARK: - Private Helpers

    /// Runs the once-per-day housekeeping and, on the first open of a new day,
    /// generates today's picks automatically. If picks already exist (or the
    /// user reset them today) it just reloads what's there.
    private func loadOrAutoGenerate() {
        let viewModel = TodayViewModel(context: context)
        try? viewModel.monthRolloverIfNeeded()
        poolWarningText = (try? viewModel.poolWarning()) ?? nil

        let existing = (try? viewModel.loadTodayPicks()) ?? []
        if existing.isEmpty, lastAutoGeneratedDay != todayKey {
            let generated = (try? viewModel.generateTodayPicks()) ?? []
            if !generated.isEmpty {
                lastAutoGeneratedDay = todayKey
            }
        }

        refreshTodayPicks()
    }

    private var todayKey: String {
        let comps = Calendar.current.dateComponents([.year, .month, .day], from: Date())
        return "\(comps.year ?? 0)-\(comps.month ?? 0)-\(comps.day ?? 0)"
    }

    private func refreshTodayPicks() {
        let viewModel = TodayViewModel(context: context)
        let people = (try? viewModel.loadTodayPicks()) ?? []
        guard !people.isEmpty else {
            withMotion(.easeInOut(duration: 0.25)) {
                todayPicks = []
            }
            refreshMonthlyProgress()
            refreshStreak()
            return
        }

        // Build the rows from Core Data immediately; phone numbers are
        // resolved from the Contacts store asynchronously so we never block
        // the main thread on every appear/foreground/tab switch.
        let rebuilt: [HomePick] = people.compactMap { person in
            guard let identifier = person.contactIdentifier else { return nil }
            return HomePick(
                identifier: identifier,
                displayName: person.displayName ?? "Unknown",
                lastConnectedText: lastConnectedText(for: person),
                hasConnectedBefore: person.lastCalledAt != nil,
                note: person.note,
                connectedToday: isConnectedToday(person)
            )
        }

        withMotion(.spring(response: 0.45, dampingFraction: 0.85)) {
            todayPicks = rebuilt
        }

        refreshMonthlyProgress()
        refreshStreak()
    }

    private func isConnectedToday(_ person: Person) -> Bool {
        guard let last = person.lastCalledAt else { return false }
        return Calendar.current.isDateInToday(last)
    }

    /// Runs the given state change with an animation, unless the user has asked
    /// the system to reduce motion — in which case it applies instantly.
    private func withMotion(_ animation: Animation, _ change: () -> Void) {
        if reduceMotion {
            change()
        } else {
            withAnimation(animation, change)
        }
    }

    private func refreshStreak() {
        let request: NSFetchRequest<ConnectionEvent> = ConnectionEvent.fetchRequest()
        request.sortDescriptors = [NSSortDescriptor(key: "date", ascending: false)]
        guard let events = try? context.fetch(request) else {
            currentStreak = 0
            return
        }
        currentStreak = NotificationsService.streaks(from: events).current
    }

    // MARK: - Actions
    private func generateTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            let picks = try viewModel.generateTodayPicks()
            guard !picks.isEmpty else {
                todayPicks = []
                return
            }
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t generate today’s pick."
            showConnectError = true
        }
    }

    private func resetTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            try viewModel.resetTodayPicks()
            // Mark today as handled so auto-generate doesn't immediately
            // recreate the set the user just cleared.
            lastAutoGeneratedDay = todayKey
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t reset today’s pick."
            showConnectError = true
        }
    }

    /// Opens the rich info card (profile, actions, note, birthday, history) for
    /// this pick — the single place all connect/mark/snooze/note actions live.
    private func openInfoCard(for pick: HomePick) {
        let viewModel = TodayViewModel(context: context)
        selectedInfoPerson = try? viewModel.person(for: pick.identifier)
    }

    /// Undoes a mis-tapped "connected today" straight from the card.
    private func undoConnected(_ pick: HomePick) {
        do {
            let viewModel = TodayViewModel(context: context)
            if let person = try viewModel.person(for: pick.identifier) {
                Haptics.light()
                try viewModel.unmarkConnectedToday(person)
            }
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t undo this connection."
            showConnectError = true
        }
    }

    private func refreshMonthlyProgress() {
        let calendar = Calendar.current
        let now = Date()
        let startOfMonth = calendar.date(from: calendar.dateComponents([.year, .month], from: now)) ?? now

        // A simple running count of this month's connections to celebrate — no
        // target or quota. markCalled already dedups to one per contact per day.
        let request: NSFetchRequest<ConnectionEvent> = ConnectionEvent.fetchRequest()
        request.predicate = NSPredicate(format: "date >= %@", startOfMonth as NSDate)
        monthlyConnectedCount = (try? context.count(for: request)) ?? 0
    }

    private static let relativeDateFormatter: RelativeDateTimeFormatter = {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .full
        return formatter
    }()

    private func lastConnectedText(for person: Person) -> String {
        if let lastCalledAt = person.lastCalledAt {
            return "Last connected: " + Self.relativeDateFormatter.localizedString(for: lastCalledAt, relativeTo: Date())
        }
        return "Not connected yet"
    }

    private func lightHaptic() { Haptics.light() }
}

// MARK: - Home Header

/// The top-of-screen header: a time-aware greeting as the editorial serif line,
/// today's date beneath it, the streak flame when there's momentum, and a quiet
/// overflow menu that houses Reset (only surfaced when there are picks to reset).
private struct HomeHeader: View {
    let greeting: String
    let dateText: String
    let streak: Int
    let canReset: Bool
    let onReset: () -> Void

    var body: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 4) {
                Text(greeting)
                    .displayTitle()

                Text(dateText)
                    .font(.subheadline)
                    .foregroundStyle(Theme.Palette.textSecondary)
            }
            .accessibilityElement(children: .combine)

            Spacer(minLength: Theme.Space.sm)

            HStack(spacing: 10) {
                StreakFlame(streak: streak)

                if canReset {
                    Menu {
                        Button(role: .destructive, action: onReset) {
                            Label("Reset today’s picks", systemImage: "arrow.counterclockwise")
                        }
                    } label: {
                        Image(systemName: "ellipsis")
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(Theme.Palette.textSecondary)
                            .frame(width: 34, height: 34)
                            .background(Circle().fill(Theme.Palette.textSecondary.opacity(0.12)))
                    }
                    .accessibilityLabel("More options")
                }
            }
            .padding(.top, 4)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

// MARK: - Home Empty State

/// A warm, centered empty state — a soft symbol motif above the copy, so an
/// empty day still feels inviting rather than blank.
private struct HomeEmptyState: View {
    /// Custom asset-catalog illustration; falls back to `symbol` when nil.
    var illustration: String? = nil
    let symbol: String
    let title: String
    let message: String

    var body: some View {
        VStack(spacing: Theme.Space.sm) {
            if let illustration {
                Image(illustration)
                    .resizable()
                    .scaledToFit()
                    .frame(width: 84, height: 84)
                    .padding(.bottom, 2)
            } else {
                Image(systemName: symbol)
                    .font(.system(size: 30, weight: .light))
                    .foregroundStyle(Theme.Palette.brand)
                    .padding(.bottom, 2)
            }

            Text(title)
                .font(.subheadline.weight(.semibold))
                .foregroundStyle(Theme.Palette.textPrimary)

            Text(message)
                .font(.footnote)
                .foregroundStyle(Theme.Palette.textSecondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .accessibilityElement(children: .combine)
    }
}

// MARK: - Today Picks Carousel

/// A swipeable set of big pick cards — one person per page, with page dots when
/// there's more than one. Presentation only; every action is delegated to the
/// closures the Home screen supplies, so this stays free of Core Data.
private struct HomePicksCarousel: View {
    let picks: [HomePick]
    let onOpenDetails: (HomePick) -> Void
    let onUndo: (HomePick) -> Void

    @State private var selection: String?

    /// A fixed height keeps the paged TabView from collapsing and stops the
    /// layout from jumping as cards with/without notes swap in.
    private let cardHeight: CGFloat = 300

    var body: some View {
        Group {
            if picks.count == 1, let pick = picks.first {
                card(for: pick)
            } else {
                TabView(selection: $selection) {
                    ForEach(picks, id: \.identifier) { pick in
                        card(for: pick)
                            .padding(.bottom, 28) // room for the page dots
                            .tag(Optional(pick.identifier))
                    }
                }
                .tabViewStyle(.page(indexDisplayMode: .always))
                .indexViewStyle(.page(backgroundDisplayMode: .always))
            }
        }
        .frame(height: cardHeight)
        .onAppear { if selection == nil { selection = picks.first?.identifier } }
    }

    private func card(for pick: HomePick) -> some View {
        HomePickCard(
            pick: pick,
            onOpenDetails: { onOpenDetails(pick) },
            onUndo: { onUndo(pick) }
        )
    }
}

// MARK: - Home Pick Card

/// One person as a large card. It's a single tappable surface that opens the
/// full info card (where Call / Message / Done / Not today live). When the
/// person has already been reached today it shows a calm "Connected today"
/// state with an Undo instead of the details hint.
private struct HomePickCard: View {
    let pick: HomePick
    let onOpenDetails: () -> Void
    let onUndo: () -> Void

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        VStack(spacing: 14) {
            ContactAvatarInlineView(
                contactIdentifier: pick.identifier,
                displayName: pick.displayName,
                size: 76
            )

            VStack(spacing: 6) {
                Text(pick.displayName)
                    .font(.title2.weight(.bold))
                    .foregroundStyle(Theme.Palette.textPrimary)
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)

                Text(pick.lastConnectedText)
                    .font(.subheadline)
                    .foregroundStyle(Theme.Palette.textSecondary)
                    .lineLimit(1)

                if let note = pick.note, !note.isEmpty {
                    Label(note, systemImage: "quote.opening")
                        .font(.footnote)
                        .italic()
                        .foregroundStyle(Theme.Palette.brand)
                        .lineLimit(2)
                        .multilineTextAlignment(.center)
                        .padding(.top, 2)
                }
            }

            Spacer(minLength: 8)

            if pick.connectedToday {
                // Reached today — no Done / Not today, just a calm confirmation
                // and an Undo for mis-taps.
                HStack(spacing: 8) {
                    Image(systemName: "checkmark.circle.fill")
                        .foregroundStyle(Theme.Palette.success)
                    Text("Connected today")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(Theme.Palette.textPrimary)

                    Spacer()

                    Button("Undo", action: onUndo)
                        .font(.subheadline.weight(.semibold))
                        .buttonStyle(.plain)
                        .foregroundStyle(Theme.Palette.textSecondary)
                }
                .padding(.horizontal, 4)
            } else {
                HStack(spacing: 6) {
                    Chip(
                        text: pick.hasConnectedBefore ? "Connected before" : "New",
                        tint: pick.hasConnectedBefore ? Theme.Palette.success : Theme.Palette.brand,
                        fillOpacity: pick.hasConnectedBefore ? 0.16 : 0.14
                    )
                    .fixedSize()

                    Spacer()

                    Label("Tap for details", systemImage: "chevron.right")
                        .labelStyle(TrailingIconLabelStyle())
                        .font(.subheadline.weight(.medium))
                        .foregroundStyle(Theme.Palette.brand)
                }
                .padding(.horizontal, 4)
            }
        }
        .padding(20)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .heroSurface(radius: Theme.Radius.hero)
        .contentShape(Rectangle())
        .onTapGesture(perform: onOpenDetails)
        .animation(reduceMotion ? nil : .easeInOut(duration: 0.25), value: pick.connectedToday)
        .accessibilityElement(children: .combine)
        .accessibilityHint("Opens \(pick.displayName)’s details and actions.")
    }
}

/// Puts a label's icon after its title (SwiftUI defaults to icon-first).
private struct TrailingIconLabelStyle: LabelStyle {
    func makeBody(configuration: Configuration) -> some View {
        HStack(spacing: 4) {
            configuration.title
            configuration.icon.font(.caption.weight(.bold))
        }
    }
}

// MARK: - Preview

#Preview {
    HomeView(selectedTab: .constant(.home))
}
