import Contacts
import CoreData
import SwiftUI
import UIKit

// MARK: - Supporting Types
private struct HomePick: Equatable {
    // MARK: - Properties
    let identifier: String
    let displayName: String
    let phoneNumber: String?
    let lastConnectedText: String
    let hasConnectedBefore: Bool
    let note: String?
}

struct HomeView: View {
    // MARK: - Bindings
    @Binding var selectedTab: AppTab

    // MARK: - Environment
    @Environment(\.openURL) private var openURL
    @Environment(\.managedObjectContext) private var context
    @Environment(\.scenePhase) private var scenePhase
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    // MARK: - State
    @State private var showConnectSheet = false
    @State private var connectErrorMessage: String?
    @State private var showConnectError = false
    @State private var todayPicks: [HomePick] = []
    @State private var selectedPick: HomePick?
    @State private var showResetConfirm = false
    @State private var showingPickDetails = false
    @State private var monthlyConnectedCount = 0
    @State private var monthlyTargetCount = 0
    @State private var showSnoozeOptions = false
    @State private var snoozeTarget: HomePick?
    @State private var noteDraft = ""
    @State private var poolWarningText: String?
    @State private var currentStreak = 0
    // Identifier of the pick that was just marked connected, used to play a
    // brief celebration on its row. Cleared shortly after.
    @State private var justConnectedID: String?

    // Remembers the day we last auto-generated (or the user reset) so opening
    // the app repeatedly doesn't regenerate a set the user cleared on purpose.
    @AppStorage("lastAutoGeneratedDay") private var lastAutoGeneratedDay = ""

    // MARK: - View
    var body: some View {
        NavigationStack {
            VStack(alignment: .leading, spacing: 20) {
                let hasTodayPick = !todayPicks.isEmpty
                let shouldShowProgressBanner = hasTodayPick || monthlyTargetCount > 0
                // Header
                HomeHeader(
                    greeting: greeting,
                    dateText: todayDateText,
                    streak: currentStreak
                )
                .confirmationDialog(
                    "Connect with \((selectedPick ?? todayPicks.first)?.displayName ?? "today’s pick")",
                    isPresented: $showConnectSheet,
                    titleVisibility: .visible
                ) {
                    if let pick = (selectedPick ?? todayPicks.first),
                       let phone = pick.phoneNumber, !phone.isEmpty {
                        Button("Call") {
                            connectAndLog(.tel, value: phone, pick: pick)
                        }
                        Button("Message") {
                            connectAndLog(.sms, value: phone, pick: pick)
                        }
                    } else {
                        Button("No number available", role: .destructive) { }
                            .disabled(true)
                    }

                    Button("Cancel", role: .cancel) { }
                }
                .alert("Can’t Connect", isPresented: $showConnectError) {
                    Button("OK", role: .cancel) { }
                } message: {
                    Text(connectErrorMessage ?? "Something went wrong.")
                }
                .sheet(isPresented: $showingPickDetails) {
                    VStack(alignment: .leading, spacing: 16) {
                        Text((selectedPick ?? todayPicks.first)?.displayName ?? "No pick")
                            .font(.title2)
                            .fontWeight(.bold)

                        if let phone = (selectedPick ?? todayPicks.first)?.phoneNumber {
                            Text(phone)
                                .foregroundStyle(Theme.Palette.textSecondary)
                        }

                        Text((selectedPick ?? todayPicks.first)?.lastConnectedText ?? "Generate a pick or add more people to your pool")
                            .foregroundStyle(Theme.Palette.textSecondary)

                        VStack(alignment: .leading, spacing: 8) {
                            Text("Note")
                                .font(.subheadline.weight(.semibold))
                                .foregroundStyle(Theme.Palette.textPrimary)

                            TextField("e.g. ask about her new job", text: $noteDraft, axis: .vertical)
                                .lineLimit(1...3)
                                .textFieldStyle(.roundedBorder)

                            Text("A quick memory jog for next time you reach out.")
                                .font(.caption)
                                .foregroundStyle(Theme.Palette.textSecondary)
                        }

                        Button("Save Note") {
                            if let pick = (selectedPick ?? todayPicks.first) {
                                saveNote(for: pick)
                            }
                        }
                        .buttonStyle(PrimaryPillButtonStyle())

                        Spacer()
                    }
                    .padding()
                    .presentationDetents([.medium])
                    .onAppear {
                        noteDraft = (selectedPick ?? todayPicks.first)?.note ?? ""
                    }
                }

                if let warning = poolWarningText {
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundStyle(Theme.Palette.warning)
                        Text(warning)
                            .font(.footnote)
                            .foregroundStyle(Theme.Palette.textSecondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(12)
                    .background(
                        RoundedRectangle(cornerRadius: 14, style: .continuous)
                            .fill(Theme.Palette.warning.opacity(0.12))
                    )
                    .accessibilityElement(children: .combine)
                }

                if shouldShowProgressBanner {
                    VStack(alignment: .leading, spacing: 14) {
                        VStack(alignment: .leading, spacing: 12) {
                            HStack(alignment: .center) {
                                VStack(alignment: .leading, spacing: 4) {
                                    Text("Today’s Picks")
                                        .font(.headline)
                                        .fontWeight(.semibold)
                                        .foregroundStyle(Theme.Palette.textPrimary)
                                    Text("Tap a person to view details or connect")
                                        .font(.subheadline)
                                        .foregroundStyle(Theme.Palette.textSecondary)
                                }
                                Spacer()
                                Image(systemName: "sparkles")
                                    .font(.title3)
                                    .foregroundStyle(Theme.Palette.brand)
                            }

                            VStack(alignment: .leading, spacing: 8) {
                                HStack(alignment: .firstTextBaseline) {
                                    Text(monthlyReachedLabel)
                                        .font(.subheadline)
                                        .fontWeight(.medium)
                                        .foregroundStyle(Theme.Palette.textPrimary)
                                    Spacer()
                                    Text(progressMessage)
                                        .font(.caption)
                                        .foregroundStyle(Theme.Palette.textSecondary)
                                }

                                ProgressView(value: monthlyProgress)
                                    .tint(progressTintColor)
                                    .animation(reduceMotion ? nil : .spring(response: 0.5, dampingFraction: 0.8), value: monthlyProgress)
                            }
                        }

                        if hasTodayPick {
                            VStack(spacing: 0) {
                                ForEach(Array(todayPicks.enumerated()), id: \.element.identifier) { entry in
                                    let index = entry.offset
                                    let pick = entry.element

                                    TodayPickRow(
                                        pick: pick,
                                        isCelebrating: justConnectedID == pick.identifier,
                                        onConnect: {
                                            selectedPick = pick
                                            lightHaptic()
                                            showConnectSheet = true
                                        },
                                        onDone: {
                                            lightHaptic()
                                            markPickAsCalled(pick)
                                        },
                                        onSnooze: {
                                            snoozeTarget = pick
                                            lightHaptic()
                                            showSnoozeOptions = true
                                        },
                                        onOpenDetails: {
                                            selectedPick = pick
                                            lightHaptic()
                                            showingPickDetails = true
                                        }
                                    )
                                    .transition(
                                        .move(edge: .trailing).combined(with: .opacity)
                                    )

                                    if index < todayPicks.count - 1 {
                                        Divider()
                                            .overlay(Theme.Palette.divider)
                                            .padding(.leading, 58)
                                    }
                                }
                            }
                            .padding(.horizontal, 10)
                            .padding(.vertical, 4)
                            .cardSurface(radius: 18, strokeOpacity: 0.8)
                        } else {
                            HomeEmptyState(
                                illustration: "AllDoneMoon",
                                symbol: "hands.sparkles",
                                title: "No pick for today",
                                message: "Tap Generate to create today’s picks. Your monthly progress is still saved below."
                            )
                            .padding(.vertical, 14)
                            .padding(.horizontal, 12)
                            .cardSurface(radius: 16, strokeOpacity: 0.8)
                        }
                    }
                    .padding(18)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .heroSurface(radius: 24)
                } else {
                    HomeEmptyState(
                        illustration: "AllDoneMoon",
                        symbol: "hands.sparkles",
                        title: "No pick for today",
                        message: "Generate a pick or add more people to your pool."
                    )
                    .padding(.vertical, 20)
                    .padding(.horizontal, 12)
                    .cardSurface(radius: 20)
                }

                Spacer(minLength: 12)

                // Action area — one clear primary (Generate), with Pool and
                // Reset as quiet secondary links so they don't compete with it
                // or crowd the bottom of the screen.
                VStack(spacing: 14) {
                    Button(action: {
                        lightHaptic()
                        generateTodayPick()
                    }) {
                        Label(hasTodayPick ? "Regenerate Picks" : "Generate Picks", systemImage: "sparkles")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(PrimaryPillButtonStyle())
                    .accessibilityHint("Create today’s picks using your current rules.")

                    HStack(spacing: 16) {
                        Button {
                            lightHaptic()
                            selectedTab = .pool
                        } label: {
                            Label("View Pool", systemImage: "person.2")
                        }
                        .tint(Theme.Palette.brand)
                        .accessibilityHint("Open your saved relationship pool.")

                        Spacer()

                        if hasTodayPick {
                            Button {
                                lightHaptic()
                                showResetConfirm = true
                            } label: {
                                Label("Reset today", systemImage: "arrow.counterclockwise")
                            }
                            .tint(Theme.Palette.textSecondary)
                            .accessibilityHint("Remove today’s picks so you can generate a fresh set.")
                        }
                    }
                    .font(.subheadline.weight(.medium))
                    .padding(.horizontal, 4)

                    Text("Small, steady check-ins build real connection.")
                        .font(.footnote)
                        .foregroundStyle(Theme.Palette.textSecondary)
                        .frame(maxWidth: .infinity, alignment: .center)
                        .padding(.top, 2)
                }
                .confirmationDialog(
                    "Reset today’s pick?",
                    isPresented: $showResetConfirm,
                    titleVisibility: .visible
                ) {
                    Button("Reset", role: .destructive) {
                        resetTodayPick()
                    }
                    Button("Cancel", role: .cancel) { }
                } message: {
                    Text("This will remove today’s saved pick and generate a fresh one the next time you tap Generate.")
                }
                .confirmationDialog(
                    "Not today for \(snoozeTarget?.displayName ?? "this person")?",
                    isPresented: $showSnoozeOptions,
                    titleVisibility: .visible
                ) {
                    Button("Just for today") {
                        if let pick = snoozeTarget { snooze(pick, days: 1) }
                    }
                    Button("Snooze for a week") {
                        if let pick = snoozeTarget { snooze(pick, days: 7) }
                    }
                    Button("Cancel", role: .cancel) { }
                } message: {
                    Text("We’ll gently set them aside and suggest someone else instead.")
                }
            }
            .padding()
            .padding(.bottom, Theme.Layout.tabBarClearance)
            .background(Theme.Palette.background.ignoresSafeArea())
            .onAppear {
                loadOrAutoGenerate()
            }
            .onChange(of: selectedTab) { _, newTab in
                if newTab == .home {
                    loadOrAutoGenerate()
                }
            }
            .onChange(of: scenePhase) { _, newPhase in
                if newPhase == .active {
                    loadOrAutoGenerate()
                }
            }
        }
    }

    // MARK: - Derived Values

    /// A warm, time-of-day greeting for the header.
    private var greeting: String {
        switch Calendar.current.component(.hour, from: Date()) {
        case 5..<12: return "Good morning"
        case 12..<17: return "Good afternoon"
        case 17..<22: return "Good evening"
        default: return "Hello"
        }
    }

    private var todayDateText: String {
        Date().formatted(.dateTime.weekday(.wide).month(.abbreviated).day())
    }

    private var monthlyProgress: Double {
        guard monthlyTargetCount > 0 else { return 0 }
        return min(Double(monthlyConnectedCount) / Double(monthlyTargetCount), 1.0)
    }

    // Warm, forward-looking copy. We deliberately avoid pace/behind framing —
    // the goal is a gentle nudge, never guilt about a number you "should" hit.
    private var monthlyReachedLabel: String {
        switch monthlyConnectedCount {
        case 0:
            return "Reach out to someone today"
        case 1:
            return "1 person reached this month"
        default:
            return "\(monthlyConnectedCount) reached this month"
        }
    }

    private var progressMessage: String {
        if monthlyConnectedCount == 0 {
            return "A fresh start"
        }
        if monthlyTargetCount > 0, monthlyConnectedCount >= monthlyTargetCount {
            return "You’re on a roll"
        }
        return "Keep it going"
    }

    private var progressTintColor: Color {
        if monthlyTargetCount > 0, monthlyConnectedCount >= monthlyTargetCount {
            return Theme.Palette.success
        }
        return Theme.Palette.brand
    }

    // MARK: - Private Helpers

    /// Runs the once-per-day housekeeping and, on the first open of a new day,
    /// generates today's picks automatically. If picks already exist (or the
    /// user reset them today) it just reloads what's there.
    private func loadOrAutoGenerate() {
        let viewModel = TodayViewModel(context: context)
        try? viewModel.monthRolloverIfNeeded()
        poolWarningText = (try? viewModel.poolWarning()) ?? nil

        let existing = (try? viewModel.loadTodayPicks()) ?? []
        if existing.isEmpty, lastAutoGeneratedDay != todayKey {
            let generated = (try? viewModel.generateTodayPicks()) ?? []
            if !generated.isEmpty {
                lastAutoGeneratedDay = todayKey
            }
        }

        refreshTodayPicks()
    }

    private var todayKey: String {
        let comps = Calendar.current.dateComponents([.year, .month, .day], from: Date())
        return "\(comps.year ?? 0)-\(comps.month ?? 0)-\(comps.day ?? 0)"
    }

    private func refreshTodayPicks() {
        let viewModel = TodayViewModel(context: context)
        let people = (try? viewModel.loadTodayPicks()) ?? []
        guard !people.isEmpty else {
            withMotion(.easeInOut(duration: 0.25)) {
                todayPicks = []
            }
            selectedPick = nil
            refreshMonthlyProgress()
            refreshStreak()
            return
        }

        // Build the rows from Core Data immediately; phone numbers are
        // resolved from the Contacts store asynchronously so we never block
        // the main thread on every appear/foreground/tab switch.
        let rebuilt: [HomePick] = people.compactMap { person in
            guard let identifier = person.contactIdentifier else { return nil }
            return HomePick(
                identifier: identifier,
                displayName: person.displayName ?? "Unknown",
                phoneNumber: nil,
                lastConnectedText: lastConnectedText(for: person),
                hasConnectedBefore: person.lastCalledAt != nil,
                note: person.note
            )
        }

        withMotion(.spring(response: 0.45, dampingFraction: 0.85)) {
            todayPicks = rebuilt
        }

        selectedPick = todayPicks.first
        refreshMonthlyProgress()
        refreshStreak()

        let identifiers = todayPicks.map(\.identifier)
        Task {
            let numbers = await Self.loadPhoneNumbers(for: identifiers)
            applyPhoneNumbers(numbers)
        }
    }

    /// Runs the given state change with an animation, unless the user has asked
    /// the system to reduce motion — in which case it applies instantly.
    private func withMotion(_ animation: Animation, _ change: () -> Void) {
        if reduceMotion {
            change()
        } else {
            withAnimation(animation, change)
        }
    }

    private func refreshStreak() {
        let request: NSFetchRequest<ConnectionEvent> = ConnectionEvent.fetchRequest()
        request.sortDescriptors = [NSSortDescriptor(key: "date", ascending: false)]
        guard let events = try? context.fetch(request) else {
            currentStreak = 0
            return
        }
        currentStreak = NotificationsService.streaks(from: events).current
    }

    private func applyPhoneNumbers(_ numbers: [String: String]) {
        guard !numbers.isEmpty else { return }

        todayPicks = todayPicks.map { pick in
            guard let number = numbers[pick.identifier] else { return pick }
            return HomePick(
                identifier: pick.identifier,
                displayName: pick.displayName,
                phoneNumber: number,
                lastConnectedText: pick.lastConnectedText,
                hasConnectedBefore: pick.hasConnectedBefore,
                note: pick.note
            )
        }

        if let selectedID = selectedPick?.identifier {
            selectedPick = todayPicks.first { $0.identifier == selectedID }
        } else {
            selectedPick = todayPicks.first
        }
    }

    // MARK: - Actions
    private func generateTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            let picks = try viewModel.generateTodayPicks()
            guard !picks.isEmpty else {
                todayPicks = []
                selectedPick = nil
                return
            }
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t generate today’s pick."
            showConnectError = true
        }
    }

    private func resetTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            try viewModel.resetTodayPicks()
            // Mark today as handled so auto-generate doesn't immediately
            // recreate the set the user just cleared.
            lastAutoGeneratedDay = todayKey
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t reset today’s pick."
            showConnectError = true
        }
    }

    private func markPickAsCalled(_ pick: HomePick) {
        do {
            let viewModel = TodayViewModel(context: context)
            if let person = try viewModel.person(for: pick.identifier) {
                try viewModel.markCalled(person)
            }
            celebrateConnection(for: pick.identifier)
            refreshTodayPicks()
            refreshMonthlyProgress()
            refreshStreak()
        } catch {
            connectErrorMessage = "Couldn’t mark this contact as called."
            showConnectError = true
        }
    }

    /// The little payoff for reaching out — a success haptic plus a brief badge
    /// on the person's row. Deliberately short and quiet, in keeping with the
    /// app's calm tone.
    private func celebrateConnection(for identifier: String) {
        successHaptic()
        withMotion(.spring(response: 0.4, dampingFraction: 0.6)) {
            justConnectedID = identifier
        }
        Task {
            try? await Task.sleep(for: .seconds(1.4))
            withMotion(.easeOut(duration: 0.3)) {
                if justConnectedID == identifier { justConnectedID = nil }
            }
        }
    }

    private func saveNote(for pick: HomePick) {
        do {
            let viewModel = TodayViewModel(context: context)
            try viewModel.setNote(noteDraft, forContactIdentifier: pick.identifier)
            refreshTodayPicks()
            showingPickDetails = false
        } catch {
            connectErrorMessage = "Couldn’t save this note."
            showConnectError = true
        }
    }

    private func snooze(_ pick: HomePick, days: Int) {
        do {
            let viewModel = TodayViewModel(context: context)
            guard let person = try viewModel.person(for: pick.identifier) else { return }

            // Snooze from the start of the day so "just for today" makes them
            // eligible again tomorrow, not at the same clock time.
            let calendar = Calendar.current
            let base = calendar.startOfDay(for: Date())
            let until = calendar.date(byAdding: .day, value: days, to: base) ?? Date()

            try viewModel.snoozePick(person, until: until)
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t snooze this pick."
            showConnectError = true
        }
    }

    private func refreshMonthlyProgress() {
        let calendar = Calendar.current
        let now = Date()

        let startOfMonth = calendar.date(from: calendar.dateComponents([.year, .month], from: now)) ?? now
        let range = calendar.range(of: .day, in: .month, for: now)
        let daysInMonth = range?.count ?? 30

        let picksPerDay: Int
        do {
            picksPerDay = max(try AppSettings.effective(in: context).picksPerDay, 0)
        } catch {
            monthlyConnectedCount = 0
            monthlyTargetCount = 0
            return
        }

        monthlyTargetCount = picksPerDay * daysInMonth

        // Progress denominator: picksPerDay * daysInMonth. The numerator counts
        // ConnectionEvents this month, which markCalled already dedups to at most
        // one per contact per day — so this is "unique contact-days connected"
        // versus the monthly goal, not a raw tap count.
        let request: NSFetchRequest<ConnectionEvent> = ConnectionEvent.fetchRequest()
        request.predicate = NSPredicate(format: "date >= %@", startOfMonth as NSDate)

        guard let monthlyConnections = try? context.count(for: request) else {
            monthlyConnectedCount = 0
            return
        }

        monthlyConnectedCount = monthlyConnections
    }

    /// Resolves phone numbers for the given contact identifiers off the main
    /// thread. Runs on a detached background task so the Contacts store work
    /// never blocks UI updates.
    private static func loadPhoneNumbers(for identifiers: [String]) async -> [String: String] {
        await Task.detached(priority: .utility) {
            let store = CNContactStore()
            let keys: [CNKeyDescriptor] = [CNContactPhoneNumbersKey as CNKeyDescriptor]

            var result: [String: String] = [:]
            for identifier in identifiers where !identifier.isEmpty {
                let predicate = CNContact.predicateForContacts(withIdentifiers: [identifier])
                if let contact = try? store.unifiedContacts(matching: predicate, keysToFetch: keys).first,
                   let number = contact.phoneNumbers.first?.value.stringValue {
                    result[identifier] = number
                }
            }
            return result
        }.value
    }

    private static let relativeDateFormatter: RelativeDateTimeFormatter = {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .full
        return formatter
    }()

    private func lastConnectedText(for person: Person) -> String {
        if let lastCalledAt = person.lastCalledAt {
            return "Last connected: " + Self.relativeDateFormatter.localizedString(for: lastCalledAt, relativeTo: Date())
        }
        return "Not connected yet"
    }

    /// Opens the call/message link and, when it actually launches, records the
    /// check-in automatically — so reaching out is the only step the user takes.
    /// (markCalled dedups to one connection per contact per day.)
    private func connectAndLog(_ scheme: PhoneLink.Scheme, value: String, pick: HomePick) {
        guard connectVia(scheme, value: value) else { return }
        markPickAsCalled(pick)
    }

    @discardableResult
    private func connectVia(_ scheme: PhoneLink.Scheme, value: String) -> Bool {
        guard let url = PhoneLink.url(scheme, number: value) else {
            connectErrorMessage = "No valid phone number for this contact."
            showConnectError = true
            return false
        }

        successHaptic()
        openURL(url)
        return true
    }

    private func lightHaptic() { Haptics.light() }

    private func successHaptic() { Haptics.success() }
}

// MARK: - Home Header

/// The top-of-screen header: a time-aware greeting, the serif app title with
/// today's date, and the streak flame when there's momentum to celebrate.
private struct HomeHeader: View {
    let greeting: String
    let dateText: String
    let streak: Int

    var body: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 2) {
                Text(greeting)
                    .font(.subheadline.weight(.medium))
                    .foregroundStyle(Theme.Palette.textSecondary)

                Text("StayConnected")
                    .displayTitle()

                Text(dateText)
                    .font(.subheadline)
                    .foregroundStyle(Theme.Palette.textSecondary)
            }

            Spacer(minLength: Theme.Space.sm)

            StreakFlame(streak: streak)
                .padding(.top, 4)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .accessibilityElement(children: .combine)
    }
}

// MARK: - Home Empty State

/// A warm, centered empty state — a soft symbol motif above the copy, so an
/// empty day still feels inviting rather than blank.
private struct HomeEmptyState: View {
    /// Custom asset-catalog illustration; falls back to `symbol` when nil.
    var illustration: String? = nil
    let symbol: String
    let title: String
    let message: String

    var body: some View {
        VStack(spacing: Theme.Space.sm) {
            if let illustration {
                Image(illustration)
                    .resizable()
                    .scaledToFit()
                    .frame(width: 84, height: 84)
                    .padding(.bottom, 2)
            } else {
                Image(systemName: symbol)
                    .font(.system(size: 30, weight: .light))
                    .foregroundStyle(Theme.Palette.brand)
                    .padding(.bottom, 2)
            }

            Text(title)
                .font(.subheadline.weight(.semibold))
                .foregroundStyle(Theme.Palette.textPrimary)

            Text(message)
                .font(.footnote)
                .foregroundStyle(Theme.Palette.textSecondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .accessibilityElement(children: .combine)
    }
}

// MARK: - Today Pick Row

/// One person in today's set. Presentation only — all actions are delegated to
/// the closures the Home screen supplies, so this stays free of Core Data.
private struct TodayPickRow: View {
    let pick: HomePick
    let isCelebrating: Bool
    let onConnect: () -> Void
    let onDone: () -> Void
    let onSnooze: () -> Void
    let onOpenDetails: () -> Void

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        HStack(spacing: 10) {
            ContactAvatarInlineView(
                contactIdentifier: pick.identifier,
                displayName: pick.displayName
            )
            .overlay(alignment: .bottomTrailing) {
                if isCelebrating {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.subheadline)
                        .foregroundStyle(Theme.Palette.success)
                        .background(Circle().fill(Theme.Palette.card))
                        .transition(.scale.combined(with: .opacity))
                }
            }

            VStack(alignment: .leading, spacing: 4) {
                // Name gets its own full-width line so it isn't crowded by the
                // status chip; the chip moves down next to the last-connected
                // line, where there's room for both.
                Text(pick.displayName)
                    .font(.body)
                    .fontWeight(.medium)
                    .foregroundStyle(Theme.Palette.textPrimary)
                    .lineLimit(1)

                HStack(spacing: 6) {
                    Chip(
                        text: pick.hasConnectedBefore ? "Connected" : "New",
                        tint: pick.hasConnectedBefore ? Theme.Palette.success : Theme.Palette.brand,
                        fillOpacity: pick.hasConnectedBefore ? 0.16 : 0.14
                    )
                    .fixedSize()
                    .animation(reduceMotion ? nil : .spring(response: 0.4, dampingFraction: 0.7), value: pick.hasConnectedBefore)

                    Text(pick.lastConnectedText)
                        .font(.caption)
                        .foregroundStyle(Theme.Palette.textSecondary)
                        .lineLimit(1)
                }

                if let note = pick.note, !note.isEmpty {
                    Label(note, systemImage: "quote.opening")
                        .font(.caption)
                        .italic()
                        .foregroundStyle(Theme.Palette.brand)
                        .lineLimit(1)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            HStack(spacing: 6) {
                Button(action: onConnect) {
                    Image(systemName: "phone.fill")
                }
                .buttonStyle(CircularIconButtonStyle(tint: Theme.Palette.success, weight: .filled, diameter: 34))
                .accessibilityLabel("Call or message \(pick.displayName)")
                .accessibilityHint("Opens contact options for this person.")

                Button(action: onDone) {
                    Image(systemName: "checkmark")
                }
                .buttonStyle(CircularIconButtonStyle(tint: Theme.Palette.brand, diameter: 34))
                .accessibilityLabel("Mark \(pick.displayName) as connected")
                .accessibilityHint("Records that you reached out to this person today.")

                Button(action: onSnooze) {
                    Image(systemName: "moon.zzz")
                }
                .buttonStyle(CircularIconButtonStyle(tint: Theme.Palette.textSecondary, diameter: 34))
                .accessibilityLabel("Not today for \(pick.displayName)")
                .accessibilityHint("Gently defers this person and swaps in someone else.")
            }
            .fixedSize()
        }
        .padding(.vertical, 12)
        .padding(.horizontal, 4)
        .contentShape(Rectangle())
        .onTapGesture(perform: onOpenDetails)
    }
}

// MARK: - Preview

#Preview {
    HomeView(selectedTab: .constant(.home))
}
