import Contacts
import CoreData
import SwiftUI
import UIKit

// MARK: - Supporting Types
private struct HomePick: Equatable {
    // MARK: - Properties
    let identifier: String
    let displayName: String
    let phoneNumber: String?
    let lastConnectedText: String
    let hasConnectedBefore: Bool
}

// MARK: - Contact Avatar Inline View
private struct ContactAvatarInlineView: View {
    // MARK: - Properties
    let contactIdentifier: String
    let displayName: String

    @State private var image: UIImage?

    // MARK: - View
    var body: some View {
        Group {
            if let image {
                Image(uiImage: image)
                    .resizable()
                    .scaledToFill()
            } else {
                ZStack {
                    Circle()
                        .fill(Color("BrandPrimary").opacity(0.14))
                    Text(initials(from: displayName))
                        .font(.caption)
                        .fontWeight(.semibold)
                        .foregroundStyle(Color("TextPrimary"))
                }
            }
        }
        .frame(width: 42, height: 42)
        .clipShape(Circle())
        .task(id: contactIdentifier) {
            image = nil
            await loadThumbnailIfNeeded()
        }
    }
    
    // MARK: - Private Helpers
    private func loadThumbnailIfNeeded() async {
        guard image == nil, !contactIdentifier.isEmpty else { return }

        // Fetch and decode the thumbnail off the main thread.
        let identifier = contactIdentifier
        let loaded = await Task.detached(priority: .utility) { () -> UIImage? in
            let store = CNContactStore()
            let keys: [CNKeyDescriptor] = [CNContactThumbnailImageDataKey as CNKeyDescriptor]
            let predicate = CNContact.predicateForContacts(withIdentifiers: [identifier])

            guard
                let contact = try? store
                    .unifiedContacts(matching: predicate, keysToFetch: keys)
                    .first,
                let data = contact.thumbnailImageData
            else {
                return nil
            }

            return UIImage(data: data)
        }.value

        if let loaded {
            image = loaded
        }
    }

    private func initials(from name: String) -> String {
        let parts = name
            .split(separator: " ")
            .prefix(2)
            .compactMap { $0.first }
        let result = String(parts)
        return result.isEmpty ? "?" : result.uppercased()
    }
}

struct HomeView: View {
    // MARK: - Bindings
    @Binding var selectedTab: AppTab

    // MARK: - Environment
    @Environment(\.openURL) private var openURL
    @Environment(\.managedObjectContext) private var context
    @Environment(\.scenePhase) private var scenePhase

    // MARK: - State
    @State private var showConnectSheet = false
    @State private var connectErrorMessage: String?
    @State private var showConnectError = false
    @State private var todayPicks: [HomePick] = []
    @State private var selectedPick: HomePick?
    @State private var showResetConfirm = false
    @State private var showingPickDetails = false
    @State private var monthlyConnectedCount = 0
    @State private var monthlyTargetCount = 0
    @State private var monthlyExpectedByToday = 0
    @State private var poolWarningText: String?

    // Remembers the day we last auto-generated (or the user reset) so opening
    // the app repeatedly doesn't regenerate a set the user cleared on purpose.
    @AppStorage("lastAutoGeneratedDay") private var lastAutoGeneratedDay = ""

    // MARK: - View
    var body: some View {
        NavigationStack {
            VStack(alignment: .leading, spacing: 20) {
                let hasTodayPick = !todayPicks.isEmpty
                let shouldShowProgressBanner = hasTodayPick || monthlyTargetCount > 0
                // Header
                VStack(alignment: .leading, spacing: 4) {
                    Text("StayConnected")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .foregroundStyle(Color("TextPrimary"))

                    Text("Today")
                        .font(.title3)
                        .foregroundStyle(Color("TextSecondary"))
                        .confirmationDialog(
                            "Connect with \((selectedPick ?? todayPicks.first)?.displayName ?? "today’s pick")",
                            isPresented: $showConnectSheet,
                            titleVisibility: .visible
                        ) {
                            if let phone = (selectedPick ?? todayPicks.first)?.phoneNumber, !phone.isEmpty {
                                Button("Call") {
                                    connectVia(.tel, value: phone)
                                }
                                Button("Message") {
                                    connectVia(.sms, value: phone)
                                }
                            } else {
                                Button("No number available", role: .destructive) { }
                                    .disabled(true)
                            }

                            Button("Cancel", role: .cancel) { }
                        }
                        .alert("Can’t Connect", isPresented: $showConnectError) {
                            Button("OK", role: .cancel) { }
                        } message: {
                            Text(connectErrorMessage ?? "Something went wrong.")
                        }
                }
                .sheet(isPresented: $showingPickDetails) {
                    VStack(spacing: 16) {
                        Text((selectedPick ?? todayPicks.first)?.displayName ?? "No pick")
                            .font(.title2)
                            .fontWeight(.bold)

                        if let phone = (selectedPick ?? todayPicks.first)?.phoneNumber {
                            Text(phone)
                                .foregroundStyle(Color("TextSecondary"))
                        }

                        Text((selectedPick ?? todayPicks.first)?.lastConnectedText ?? "Generate a pick or add more people to your pool")
                            .foregroundStyle(Color("TextSecondary"))

                        Spacer()
                    }
                    .padding()
                    .presentationDetents([.medium])
                }

                if let warning = poolWarningText {
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundStyle(Color("Warning"))
                        Text(warning)
                            .font(.footnote)
                            .foregroundStyle(Color("TextSecondary"))
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(12)
                    .background(
                        RoundedRectangle(cornerRadius: 14, style: .continuous)
                            .fill(Color("Warning").opacity(0.12))
                    )
                    .accessibilityElement(children: .combine)
                }

                if shouldShowProgressBanner {
                    VStack(alignment: .leading, spacing: 14) {
                        VStack(alignment: .leading, spacing: 12) {
                            HStack(alignment: .center) {
                                VStack(alignment: .leading, spacing: 4) {
                                    Text("Today’s Picks")
                                        .font(.headline)
                                        .fontWeight(.semibold)
                                        .foregroundStyle(Color("TextPrimary"))
                                    Text("Tap a person to view details or connect")
                                        .font(.subheadline)
                                        .foregroundStyle(Color("TextSecondary"))
                                }
                                Spacer()
                                Image(systemName: "sparkles")
                                    .font(.title3)
                                    .foregroundStyle(Color("BrandPrimary"))
                            }

                            VStack(alignment: .leading, spacing: 8) {
                                HStack(alignment: .firstTextBaseline) {
                                    Text("\(monthlyConnectedCount) / \(monthlyTargetCount) connections this month")
                                        .font(.subheadline)
                                        .fontWeight(.medium)
                                        .foregroundStyle(Color("TextPrimary"))
                                    Spacer()
                                    Text(progressMessage)
                                        .font(.caption)
                                        .foregroundStyle(Color("TextSecondary"))
                                }

                                ProgressView(value: monthlyProgress)
                                    .tint(progressTintColor)

                                Text("Expected by today: \(monthlyExpectedByToday) picks")
                                    .font(.caption)
                                    .foregroundStyle(Color("TextSecondary"))
                            }
                        }

                        if hasTodayPick {
                            VStack(spacing: 0) {
                                ForEach(Array(todayPicks.enumerated()), id: \.element.identifier) { entry in
                                    let index = entry.offset
                                    let pick = entry.element

                                    HStack(spacing: 12) {
                                        ContactAvatarInlineView(
                                            contactIdentifier: pick.identifier,
                                            displayName: pick.displayName
                                        )

                                        VStack(alignment: .leading, spacing: 6) {
                                            HStack(spacing: 8) {
                                                Text(pick.displayName)
                                                    .font(.body)
                                                    .fontWeight(.medium)
                                                    .foregroundStyle(Color("TextPrimary"))
                                                    .multilineTextAlignment(.leading)
                                                    .lineLimit(1)

                                                Text(pick.hasConnectedBefore ? "Connected" : "New")
                                                    .font(.caption2)
                                                    .fontWeight(.semibold)
                                                    .padding(.horizontal, 8)
                                                    .padding(.vertical, 4)
                                                    .background(
                                                        Capsule()
                                                            .fill(
                                                                pick.hasConnectedBefore
                                                                ? Color("Success").opacity(0.16)
                                                                : Color("BrandPrimary").opacity(0.14)
                                                            )
                                                    )
                                                    .foregroundStyle(
                                                        pick.hasConnectedBefore
                                                        ? Color("Success")
                                                        : Color("BrandPrimary")
                                                    )
                                            }

                                            Text(pick.lastConnectedText)
                                                .font(.caption)
                                                .foregroundStyle(Color("TextSecondary"))
                                                .multilineTextAlignment(.leading)
                                                .lineLimit(2)
                                        }

                                        Spacer(minLength: 8)

                                        HStack(spacing: 8) {
                                            Button {
                                                selectedPick = pick
                                                lightHaptic()
                                                showConnectSheet = true
                                            } label: {
                                                Image(systemName: "phone.fill")
                                                    .font(.subheadline)
                                            }
                                            .buttonStyle(.borderedProminent)
                                            .tint(Color("Success"))
                                            .accessibilityLabel("Call or message \(pick.displayName)")
                                            .accessibilityHint("Opens contact options for this person.")

                                            Button {
                                                lightHaptic()
                                                markPickAsCalled(pick)
                                            } label: {
                                                Image(systemName: "checkmark")
                                                    .font(.subheadline)
                                            }
                                            .buttonStyle(.bordered)
                                            .tint(Color("BrandPrimary"))
                                            .accessibilityLabel("Mark \(pick.displayName) as connected")
                                            .accessibilityHint("Records that you reached out to this person today.")
                                        }
                                    }
                                    .padding(.vertical, 14)
                                    .padding(.horizontal, 4)
                                    .contentShape(Rectangle())
                                    .onTapGesture {
                                        selectedPick = pick
                                        lightHaptic()
                                        showingPickDetails = true
                                    }

                                    if index < todayPicks.count - 1 {
                                        Divider()
                                            .overlay(Color("Divider"))
                                            .padding(.leading, 58)
                                    }
                                }
                            }
                            .padding(.horizontal, 10)
                            .padding(.vertical, 4)
                            .background(
                                RoundedRectangle(cornerRadius: 18)
                                    .fill(Color("Card"))
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 18)
                                    .stroke(Color("Divider").opacity(0.8), lineWidth: 1)
                            )
                        } else {
                            VStack(alignment: .leading, spacing: 8) {
                                Text("No pick for today")
                                    .font(.subheadline)
                                    .fontWeight(.medium)
                                    .foregroundStyle(Color("TextPrimary"))
                                Text("Tap Generate to create today’s picks. Your monthly progress is still saved below.")
                                    .font(.footnote)
                                    .foregroundStyle(Color("TextSecondary"))
                            }
                            .padding(.vertical,14)
                            .padding(.horizontal,12)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .background(
                                RoundedRectangle(cornerRadius: 16)
                                    .fill(Color("Card"))
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 16)
                                    .stroke(Color("Divider").opacity(0.8), lineWidth: 1)
                            )
                        }
                    }
                    .padding(18)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(
                        RoundedRectangle(cornerRadius: 24)
                            .fill(
                                LinearGradient(
                                    colors: [
                                        Color("Card"),
                                        Color("BrandPrimary").opacity(0.05)
                                    ],
                                    startPoint: .topLeading,
                                    endPoint: .bottomTrailing
                                )
                            )
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: 24)
                            .stroke(Color("Divider").opacity(0.85), lineWidth: 1)
                    )
                    .shadow(color: .black.opacity(0.04), radius: 12, x: 0, y: 6)
                } else {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("No pick for today")
                            .font(.subheadline)
                            .fontWeight(.medium)
                            .foregroundStyle(Color("TextPrimary"))
                        Text("Generate a pick or add more people to your pool.")
                            .font(.footnote)
                            .foregroundStyle(Color("TextSecondary"))
                    }
                    .padding(.vertical, 14)
                    .padding(.horizontal, 12)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(
                        RoundedRectangle(cornerRadius: 20, style: .continuous)
                            .fill(Color("Card"))
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: 20, style: .continuous)
                            .stroke(Color("Divider").opacity(0.85), lineWidth: 1)
                    )
                }

                // Quick navigation
                Button {
                    lightHaptic()
                    selectedTab = .pool
                } label: {
                    Label("View Pool", systemImage: "person.2.fill")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(SecondaryPillButtonStyle())
                .accessibilityHint("Open your saved relationship pool.")

                Spacer()

                // Action buttons
                HStack(spacing: 14) {
                    Button(action: {
                        lightHaptic()
                        generateTodayPick()
                    }) {
                        Label("Generate", systemImage: "sparkles")
                    }
                    .buttonStyle(PrimaryPillButtonStyle())
                    .accessibilityHint("Create today’s picks using your current rules.")

                    Button(action: {
                        lightHaptic()
                        showResetConfirm = true
                    }) {
                        Label("Reset Today", systemImage: "arrow.counterclockwise")
                    }
                    .buttonStyle(SecondaryPillButtonStyle())
                    .disabled(!hasTodayPick)
                    .accessibilityHint("Remove today’s picks so you can generate a fresh set.")
                }
                .confirmationDialog(
                    "Reset today’s pick?",
                    isPresented: $showResetConfirm,
                    titleVisibility: .visible
                ) {
                    Button("Reset", role: .destructive) {
                        resetTodayPick()
                    }
                    Button("Cancel", role: .cancel) { }
                } message: {
                    Text("This will remove today’s saved pick and generate a fresh one the next time you tap Generate.")
                }
                .padding(.top, 6)

                // Footer text
                Text("Small consistent breaks build real connections.")
                    .font(.footnote)
                    .foregroundStyle(Color("TextSecondary"))
                    .padding(.top, 8)
            }
            .padding()
            .background(Color("Background").ignoresSafeArea())
            .onAppear {
                loadOrAutoGenerate()
            }
            .onChange(of: selectedTab) { _, newTab in
                if newTab == .home {
                    loadOrAutoGenerate()
                }
            }
            .onChange(of: scenePhase) { _, newPhase in
                if newPhase == .active {
                    loadOrAutoGenerate()
                }
            }
        }
    }

    // MARK: - Derived Values
    private var monthlyProgress: Double {
        guard monthlyTargetCount > 0 else { return 0 }
        return min(Double(monthlyConnectedCount) / Double(monthlyTargetCount), 1.0)
    }

    private var progressMessage: String {
        guard monthlyTargetCount > 0 else { return "No target yet" }

        if monthlyConnectedCount >= monthlyTargetCount {
            return "Target reached"
        }

        if monthlyConnectedCount > monthlyExpectedByToday {
            return "Ahead of pace"
        } else if monthlyConnectedCount == monthlyExpectedByToday {
            return "On pace"
        } else {
            return "Behind pace"
        }
    }

    private var progressTintColor: Color {
        switch progressMessage {
        case "Target reached":
            return Color("Success")
        case "Ahead of pace", "On pace":
            return Color("BrandPrimary")
        default:
            return Color("Warning")
        }
    }

    // MARK: - Private Helpers

    /// Runs the once-per-day housekeeping and, on the first open of a new day,
    /// generates today's picks automatically. If picks already exist (or the
    /// user reset them today) it just reloads what's there.
    private func loadOrAutoGenerate() {
        let viewModel = TodayViewModel(context: context)
        try? viewModel.monthRolloverIfNeeded()
        poolWarningText = (try? viewModel.poolWarning()) ?? nil

        let existing = (try? viewModel.loadTodayPicks()) ?? []
        if existing.isEmpty, lastAutoGeneratedDay != todayKey {
            let generated = (try? viewModel.generateTodayPicks()) ?? []
            if !generated.isEmpty {
                lastAutoGeneratedDay = todayKey
            }
        }

        refreshTodayPicks()
    }

    private var todayKey: String {
        let comps = Calendar.current.dateComponents([.year, .month, .day], from: Date())
        return "\(comps.year ?? 0)-\(comps.month ?? 0)-\(comps.day ?? 0)"
    }

    private func refreshTodayPicks() {
        let viewModel = TodayViewModel(context: context)
        let people = (try? viewModel.loadTodayPicks()) ?? []
        guard !people.isEmpty else {
            todayPicks = []
            selectedPick = nil
            refreshMonthlyProgress()
            return
        }

        // Build the rows from Core Data immediately; phone numbers are
        // resolved from the Contacts store asynchronously so we never block
        // the main thread on every appear/foreground/tab switch.
        todayPicks = people.compactMap { person in
            guard let identifier = person.contactIdentifier else { return nil }
            return HomePick(
                identifier: identifier,
                displayName: person.displayName ?? "Unknown",
                phoneNumber: nil,
                lastConnectedText: lastConnectedText(for: person),
                hasConnectedBefore: person.lastCalledAt != nil
            )
        }

        selectedPick = todayPicks.first
        refreshMonthlyProgress()

        let identifiers = todayPicks.map(\.identifier)
        Task {
            let numbers = await Self.loadPhoneNumbers(for: identifiers)
            applyPhoneNumbers(numbers)
        }
    }

    private func applyPhoneNumbers(_ numbers: [String: String]) {
        guard !numbers.isEmpty else { return }

        todayPicks = todayPicks.map { pick in
            guard let number = numbers[pick.identifier] else { return pick }
            return HomePick(
                identifier: pick.identifier,
                displayName: pick.displayName,
                phoneNumber: number,
                lastConnectedText: pick.lastConnectedText,
                hasConnectedBefore: pick.hasConnectedBefore
            )
        }

        if let selectedID = selectedPick?.identifier {
            selectedPick = todayPicks.first { $0.identifier == selectedID }
        } else {
            selectedPick = todayPicks.first
        }
    }

    // MARK: - Actions
    private func generateTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            let picks = try viewModel.generateTodayPicks()
            guard !picks.isEmpty else {
                todayPicks = []
                selectedPick = nil
                return
            }
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t generate today’s pick."
            showConnectError = true
        }
    }

    private func resetTodayPick() {
        do {
            let viewModel = TodayViewModel(context: context)
            try viewModel.resetTodayPicks()
            // Mark today as handled so auto-generate doesn't immediately
            // recreate the set the user just cleared.
            lastAutoGeneratedDay = todayKey
            refreshTodayPicks()
        } catch {
            connectErrorMessage = "Couldn’t reset today’s pick."
            showConnectError = true
        }
    }

    private func markPickAsCalled(_ pick: HomePick) {
        do {
            let viewModel = TodayViewModel(context: context)
            if let person = try viewModel.person(for: pick.identifier) {
                try viewModel.markCalled(person)
            }
            refreshTodayPicks()
            refreshMonthlyProgress()
        } catch {
            connectErrorMessage = "Couldn’t mark this contact as called."
            showConnectError = true
        }
    }

    private func refreshMonthlyProgress() {
        let calendar = Calendar.current
        let now = Date()

        let startOfMonth = calendar.date(from: calendar.dateComponents([.year, .month], from: now)) ?? now
        let range = calendar.range(of: .day, in: .month, for: now)
        let daysInMonth = range?.count ?? 30
        let dayOfMonth = calendar.component(.day, from: now)

        let settings: AppSettings?
        do {
            settings = try AppSettings.fetchOrCreate(in: context)
        } catch {
            monthlyConnectedCount = 0
            monthlyTargetCount = 0
            monthlyExpectedByToday = 0
            return
        }

        let picksPerDay = max(Int(settings?.picksPerDay ?? 0), 0)
        monthlyTargetCount = picksPerDay * daysInMonth
        monthlyExpectedByToday = min(picksPerDay * dayOfMonth, monthlyTargetCount)

        // Progress denominator: picksPerDay * daysInMonth. The numerator counts
        // ConnectionEvents this month, which markCalled already dedups to at most
        // one per contact per day — so this is "unique contact-days connected"
        // versus the monthly goal, not a raw tap count.
        let request: NSFetchRequest<ConnectionEvent> = ConnectionEvent.fetchRequest()
        request.predicate = NSPredicate(format: "date >= %@", startOfMonth as NSDate)

        guard let monthlyConnections = try? context.count(for: request) else {
            monthlyConnectedCount = 0
            return
        }

        monthlyConnectedCount = monthlyConnections
    }

    /// Resolves phone numbers for the given contact identifiers off the main
    /// thread. Runs on a detached background task so the Contacts store work
    /// never blocks UI updates.
    private static func loadPhoneNumbers(for identifiers: [String]) async -> [String: String] {
        await Task.detached(priority: .utility) {
            let store = CNContactStore()
            let keys: [CNKeyDescriptor] = [CNContactPhoneNumbersKey as CNKeyDescriptor]

            var result: [String: String] = [:]
            for identifier in identifiers where !identifier.isEmpty {
                let predicate = CNContact.predicateForContacts(withIdentifiers: [identifier])
                if let contact = try? store.unifiedContacts(matching: predicate, keysToFetch: keys).first,
                   let number = contact.phoneNumbers.first?.value.stringValue {
                    result[identifier] = number
                }
            }
            return result
        }.value
    }

    private func lastConnectedText(for person: Person) -> String {
        if let lastCalledAt = person.lastCalledAt {
            let formatter = RelativeDateTimeFormatter()
            formatter.unitsStyle = .full
            return "Last connected: " + formatter.localizedString(for: lastCalledAt, relativeTo: Date())
        }
        return "Not connected yet"
    }

    private func connectVia(_ scheme: PhoneLink.Scheme, value: String) {
        guard let url = PhoneLink.url(scheme, number: value) else {
            connectErrorMessage = "No valid phone number for this contact."
            showConnectError = true
            return
        }

        successHaptic()
        openURL(url)
    }

    private func lightHaptic() {
        let generator = UIImpactFeedbackGenerator(style: .light)
        generator.impactOccurred()
    }

    private func successHaptic() {
        let generator = UINotificationFeedbackGenerator()
        generator.notificationOccurred(.success)
    }
}

// MARK: - Preview

#Preview {
    HomeView(selectedTab: .constant(.home))
}
