import CoreData
import SwiftUI
import UIKit

struct SettingsView: View {
    @Environment(\.managedObjectContext) private var context

    // MARK: - State

    @State private var showSavedToast = false
    @State private var showNotificationPermissionAlert = false
    @State private var errorMessage: String?
    @State private var showError = false
    @State private var initialPicksPerDay: Int = 1
    @State private var initialMinGapDays: Int = 7
    @State private var initialRemindersEnabled: Bool = false
    @State private var initialReminderTime: Date = .now
    @StateObject private var viewModel: SettingsViewModel
    @AppStorage("appearanceMode") private var appearanceMode = "system"
    // Mirrors Home's marker so that, when a settings change invalidates today's
    // picks, Home auto-generates a fresh set instead of showing "No pick".
    @AppStorage("lastAutoGeneratedDay") private var lastAutoGeneratedDay = ""

    // MARK: - Derived Values

    private var hasChanges: Bool {
        (
            initialPicksPerDay != viewModel.picksPerDay
            || initialMinGapDays != viewModel.minGapDays
            || initialRemindersEnabled != viewModel.remindersEnabled
            || Calendar.current.compare(
                initialReminderTime,
                to: viewModel.reminderTime,
                toGranularity: .minute
            ) != .orderedSame
        )
    }

    // MARK: - Private Helpers

    private func successHaptic() { Haptics.success() }

    /// Saves settings and syncs reminders. Only invalidates today's picks when a
    /// pick-affecting rule (picks-per-day or minimum gap) actually changed — so
    /// tweaking appearance or the reminder time never wipes the day's picks.
    private func performSave() {
        // Capture what changed *before* we overwrite the baselines.
        let picksRulesChanged =
            initialPicksPerDay != viewModel.picksPerDay
            || initialMinGapDays != viewModel.minGapDays

        Task {
            do {
                try viewModel.save()

                if picksRulesChanged {
                    // Drop today's now-stale picks and let Home regenerate a
                    // fresh set on its next appearance (clearing the marker).
                    try viewModel.clearTodayIfNeeded()
                    lastAutoGeneratedDay = ""
                }

                try viewModel.refreshReminderPreview()

                if viewModel.remindersEnabled {
                    let allowed = try await NotificationsService.requestPermissionIfNeeded()
                    if allowed {
                        try await NotificationsService.syncReminderIfNeeded(in: context)
                    } else {
                        viewModel.remindersEnabled = false
                        try viewModel.save()
                        await NotificationsService.cancelDailyReminder()
                        showNotificationPermissionAlert = true
                    }
                } else {
                    await NotificationsService.cancelDailyReminder()
                }

                try viewModel.refreshReminderPreview()
                commitInitials()
                showSavedToast = true
                successHaptic()
            } catch {
                errorMessage = "Couldn’t save your settings. Please try again."
                showError = true
            }
        }
    }

    /// Resets the change-tracking baselines to the currently saved values so the
    /// Save button returns to its disabled "Saved" state.
    private func commitInitials() {
        initialPicksPerDay = viewModel.picksPerDay
        initialMinGapDays = viewModel.minGapDays
        initialRemindersEnabled = viewModel.remindersEnabled
        initialReminderTime = viewModel.reminderTime
    }

    // MARK: - Initialization

    init(context: NSManagedObjectContext) {
        _viewModel = StateObject(wrappedValue: SettingsViewModel(context: context))
    }

    // MARK: - View

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Settings")
                            .font(.largeTitle)
                            .fontWeight(.bold)
                            .foregroundStyle(Theme.Palette.textPrimary)

                        Text("Customize your experience")
                            .font(.title3)
                            .foregroundStyle(Theme.Palette.textSecondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.top, 8)

                    SettingsCard(title: "Call frequency", systemImage: "slider.horizontal.3") {
                        Stepper(
                            "Picks per day: \(viewModel.picksPerDay)",
                            value: $viewModel.picksPerDay,
                            in: 1...3
                        )

                        Divider().opacity(0.2)

                        Stepper(
                            "Minimum gap (days): \(viewModel.minGapDays)",
                            value: $viewModel.minGapDays,
                            in: 7...60
                        )
                    }

                    SettingsCard(title: "How picks work", systemImage: "info.circle") {
                        Text("• Picks stay the same all day unless you reset them.")
                        Text("• We try to avoid repeats for at least \(viewModel.minGapDays) days.")
                        Text("• If your pool is too small, the gap rule may relax.")
                    }
                    .font(.footnote)
                    .foregroundStyle(Theme.Palette.textSecondary)

                    SettingsCard(title: "Pool size guidance", systemImage: "person.2") {
                        SettingsRow(
                            title: "Recommended pool size",
                            value: "\(viewModel.recommendedPoolSize)+"
                        )

                        SettingsRow(
                            title: "Rule of thumb",
                            value: "\(viewModel.minGapDays) days × \(viewModel.picksPerDay) picks/day"
                        )
                    }

                    SettingsCard(title: "Appearance", systemImage: "paintbrush") {
                        VStack(alignment: .leading, spacing: 12) {
                            Picker("Appearance", selection: $appearanceMode) {
                                Text("System").tag("system")
                                Text("Light").tag("light")
                                Text("Dark").tag("dark")
                            }
                            .pickerStyle(.segmented)

                            Text("Choose whether StayConnected follows your device appearance or always uses light or dark mode.")
                                .font(.footnote)
                                .foregroundStyle(Theme.Palette.textSecondary)
                        }
                    }

                    SettingsCard(title: "Reminder", systemImage: "bell") {
                        Toggle("Daily reminder", isOn: $viewModel.remindersEnabled)
                            .accessibilityHint("Enable a notification that reflects your current progress for the day.")

                        DatePicker(
                            "Time",
                            selection: $viewModel.reminderTime,
                            displayedComponents: .hourAndMinute
                        )
                        .disabled(!viewModel.remindersEnabled)
                        .accessibilityHint("Choose when StayConnected should remind you each day.")
                    }

                    VStack(spacing: 10) {
                        Button {
                            performSave()
                        } label: {
                            Text(hasChanges ? "Save Settings" : "Saved")
                                .frame(maxWidth: .infinity)
                        }
                        .buttonStyle(PrimaryPillButtonStyle())
                        .disabled(!hasChanges)
                        .opacity(hasChanges ? 1.0 : 0.6)
                        .accessibilityHint("Save your current frequency, reminder, and appearance preferences.")

                        Text("Changes apply immediately.")
                            .font(.footnote)
                            .foregroundStyle(Theme.Palette.textSecondary)
                    }
                    .padding(.top, 8)
                }
                .padding()
                .padding(.bottom, Theme.Layout.tabBarClearance)
            }
            .background(Theme.Palette.background.ignoresSafeArea())
            .navigationBarTitleDisplayMode(.inline)
            .task {
                do {
                    try viewModel.load()

                    initialPicksPerDay = viewModel.picksPerDay
                    initialMinGapDays = viewModel.minGapDays
                    initialRemindersEnabled = viewModel.remindersEnabled
                    initialReminderTime = viewModel.reminderTime
                } catch {
                    errorMessage = "Couldn’t load your settings. Default values are shown."
                    showError = true
                }
            }
            .alert("Saved", isPresented: $showSavedToast) {
                Button("OK", role: .cancel) { }
            } message: {
                Text("Your settings have been saved.")
            }
            .alert("Something Went Wrong", isPresented: $showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(errorMessage ?? "Please try again.")
            }
            .alert("Notifications Disabled", isPresented: $showNotificationPermissionAlert) {
                Button("Open Settings") {
                    if let url = URL(string: UIApplication.openSettingsURLString) {
                        UIApplication.shared.open(url)
                    }
                }

                Button("Cancel", role: .cancel) { }
            } message: {
                Text("Daily reminders are turned off in iOS Settings. Enable notifications for StayConnected to receive reminders.")
            }
        }
    }

}

// MARK: - Subviews

private struct SettingsCard<Content: View>: View {
    // MARK: - Properties
    let title: String
    var systemImage: String? = nil
    @ViewBuilder var content: Content

    // MARK: - View
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                if let systemImage {
                    Image(systemName: systemImage)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(Theme.Palette.brand)
                }

                Text(title)
                    .font(.headline)
                    .foregroundStyle(Theme.Palette.textPrimary)
            }

            content
        }
        .padding()
        .cardSurface(radius: 20)
    }
}

private struct SettingsRow: View {
    // MARK: - Properties
    let title: String
    let value: String

    // MARK: - View
    var body: some View {
        HStack {
            Text(title)
                .foregroundStyle(Theme.Palette.textPrimary)
            Spacer()
            Text(value)
                .foregroundStyle(Theme.Palette.textSecondary)
        }
        .font(.subheadline)
    }
}

// MARK: - Preview
#Preview {
    SettingsView(context: PersistenceController.shared.container.viewContext)
}
